stages:
  - lint

checkstyle:
  stage: lint
  image: registry.gitlab.com/eyeo/docker/gitlab-codequality:21.01
  script:
    # Run checkstyle with our config against all java files
    - checkstyle --exclude=.git -c config/checkstyle/checkstyle.xml -f xml $(find . -name "*.java") -o checkstyle-report.xml || true
    # Change the paths to relative in the output so gitlab can link them properly
    - sed -i -e "s|$(pwd)/./||g" checkstyle-report.xml
    # Convert the checkstyle output to code-climate format so gitlab can parse it
    - |
      violations-command-line \
        -detail-level COMPACT \
        -code-climate code-climate-report.json \
        --violations "CHECKSTYLE" "$(pwd)" ".*checkstyle-report.xml" "Checkstyle"
  artifacts:
    reports:
      codequality:
        - code-climate-report.json


